version: '3.8'
services:
  postgres:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "9001:80"
volumes:
  postgres:
    driver: local
